/////////////////////////////////
//   DEV DUMMY PARTICIAPNTS    //
/////////////////////////////////
export const INITIAL_PARTICIPANTS_DUMMY = [
  {
    callType: "audio",
    canControl: false,
    canChangeLayout: false,
    canDisconnect: true,
    canFecc: false,
    canMute: true,
    canRaiseHand: true,
    canSpotlight: true,
    canTransfer: true,
    displayName: "Phone Presenter 282",
    overlayText: "Phone Presenter 282",
    handRaisedTime: 0,
    identity: "6aa93410-2770-4da1-8c9c-e37a37297e19",
    isCameraMuted: false,
    isConjoined: false,
    isConnecting: false,
    isEndpoint: true,
    isExternal: false,
    isIdpAuthenticated: false,
    isGateway: false,
    isHost: false,
    isMainVideoDroppedOut: false,
    isMuted: true,
    isPresenting: false,
    isSpotlight: false,
    isStreaming: false,
    isVideoSilent: false,
    isWaiting: false,
    needsPresentationInMix: false,
    protocol: "sip",
    raisedHand: false,
    role: "guest",
    rxPresentation: true,
    serviceType: "conference",
    spotlightOrder: 0,
    startAt: "2024-07-10T19:01:17.871Z",
    startTime: 1720638077.8710172,
    uri: "sip:+16467267458@185.167.190.22:6062",
    uuid: "6aa93410-2770-4da1-8c9c-e37a37297e19",
    vendor: "iOS/17.5.1 iPhone Mavenir-14042501t",
    rawData: {
      api_url: "/participants/6aa93410-2770-4da1-8c9c-e37a37297e19",
      call_direction: "in",
      display_name: "Phone Presenter 282",
      encryption: "Off",
      has_media: true,
      is_muted: "NO",
      is_presenting: "NO",
      is_streaming_conference: false,
      is_video_call: "NO",
      is_audio_only_call: "YES",
      local_alias: "52874",
      overlay_text: "Phone Presenter 282",
      presentation_supported: "NO",
      fecc_supported: "NO",
      protocol: "sip",
      role: "guest",
      rx_presentation_policy: "ALLOW",
      service_type: "conference",
      spotlight: 0,
      start_time: 1720638077.8710172,
      uri: "sip:+16467267458@185.167.190.22:6062",
      external_node_uuid: "",
      uuid: "6aa93410-2770-4da1-8c9c-e37a37297e19",
      vendor: "iOS/17.5.1 iPhone Mavenir-14042501t",
      is_external: false,
      is_conjoined: false,
      transfer_supported: "YES",
      disconnect_supported: "YES",
      mute_supported: "YES",
      buzz_time: 0,
      call_tag: "",
      is_video_muted: false,
      is_video_silent: false,
      is_main_video_dropped_out: false,
      needs_presentation_in_mix: false,
      show_live_captions: false,
      is_idp_authenticated: false,
      send_to_audio_mixes: [
        {
          mix_name: "main",
          prominent: false,
        },
      ],
      receive_from_audio_mix: "main",
      layout_group: null,
    },
  },
  {
    api_url: "/participants/5e9e053f-91de-4df1-9749-9743230b6174",
    call_direction: "in",
    displayName: "api_user",
    encryption: "On",
    has_media: false,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "NO",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "api_user",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "api",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "waiting_room",
    spotlightOrder: 1,
    start_time: 1717463486.0425053,
    uri: "api_user",
    external_node_uuid: "",
    uuid: "5e9e053f-91de-4df1-9749-9743230b6174",
    vendor:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 PexRTC",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/9fa2b838-c4e9-4c5a-813a-0ee7b44b1441",
    call_direction: "in",
    displayName: "Papi",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "YES",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "Papi",
    presentation_supported: "YES",
    fecc_supported: "NO",
    protocol: "webrtc",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 0,
    start_time: 1717463529.9298756,
    uri: "Papi",
    external_node_uuid: "",
    uuid: "9fa2b838-c4e9-4c5a-813a-0ee7b44b1441",
    vendor:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Webapp3/6.0.0+bc6f3c1cf",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 1,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },

  {
    api_url: "/participants/f4eb23e4-6403-4ad4-a61c-7844c489e638",
    call_direction: "out",
    displayName: "sip:presenter2@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter2@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "sip",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 1,
    start_time: 1717038799.2610059,
    uri: "sip:presenter2@prodfs.webcasts.com",
    external_node_uuid: "",
    uuid: "f4eb23e4-6403-4ad4-a61c-7844c489e638",
    vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/34981533-01ed-45a3-a586-4f86e8d59310",
    call_direction: "out",
    displayName: "rtmp: stream",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: true,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "rtmp: stream",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "rtmp",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 0,
    start_time: 1717038807.233808,
    uri: "sip:presenter3@prodfs.webcasts.com",
    external_node_uuid: "",
    uuid: "34981533-01ed-45a3-a586-4f86e8d59310",
    vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/4addf56c-2dbe-4303-8912-7b1355a7c322",
    call_direction: "out",
    displayName: "sip:presenter4@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "YES",
    local_alias: "52569",
    overlay_text: "presenter4@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "sip",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 1,
    start_time: 1717038815.5377162,
    uri: "sip:presenter4@prodfs.webcasts.com",
    external_node_uuid: "",
    uuid: "4addf56c-2dbe-4303-8912-7b1355a7c322",
    vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: true,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/48f0321b-4010-4a9e-9d14-50f23627929e",
    call_direction: "out",
    displayName: "sip:presenter5@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter5@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "sip",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 0,
    start_time: 1717038822.6079524,
    uri: "sip:presenter5@prodfs.webcasts.com",
    external_node_uuid: "",
    uuid: "48f0321b-4010-4a9e-9d14-50f23627929e",
    vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/923f3865-a8cd-40e3-959e-d5e19cdebd0a",
    call_direction: "in",
    display_name: "John Woo",
    encryption: "On",
    has_media: true,
    is_muted: "YES",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "Richard Felix",
    presentation_supported: "YES",
    fecc_supported: "NO",
    protocol: "webrtc",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 3,
    start_time: 1718938269.2712307,
    uri: "Richard Felix",
    external_node_uuid: "",
    uuid: "62065514-7aaa-4f4e-a73d-06ee052f2107",
    vendor:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Webapp3/6.0.0+861f7a908",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: true,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
];

/////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
const me = {
  callType: "video",
  canControl: true,
  canChangeLayout: true,
  canDisconnect: true,
  canFecc: false,
  canMute: true,
  canRaiseHand: true,
  canSpotlight: true,
  canTransfer: true,
  displayName: "Richard Felix",
  overlayText: "Richard Felix",
  handRaisedTime: 0,
  identity: "62065514-7aaa-4f4e-a73d-06ee052f2107",
  isCameraMuted: false,
  isConjoined: false,
  isConnecting: false,
  isEndpoint: false,
  isExternal: false,
  isIdpAuthenticated: false,
  isGateway: false,
  isHost: true,
  isMainVideoDroppedOut: false,
  isMuted: true,
  isPresenting: false,
  isSpotlight: false,
  isStreaming: false,
  isVideoSilent: false,
  isWaiting: false,
  needsPresentationInMix: false,
  protocol: "webrtc",
  raisedHand: false,
  role: "chair",
  rxPresentation: true,
  serviceType: "waiting_room",
  spotlightOrder: 0,
  startAt: "2024-07-01T02:33:07.098Z",
  startTime: 1719801187.0984137,
  uri: "Richard Felix",
  uuid: "648afde9-a999-492b-9d8d-5322763422ea",
  vendor:
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Webapp3/6.0.0+861f7a908",
  rawData: {
    api_url: "/participants/648afde9-a999-492b-9d8d-5322763422ea",
    call_direction: "in",
    display_name: "Richard Felix",
    encryption: "On",
    has_media: true,
    is_muted: "YES",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "Richard Felix",
    presentation_supported: "YES",
    fecc_supported: "NO",
    protocol: "webrtc",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1719801187.0984137,
    uri: "Richard Felix",
    external_node_uuid: "",
    uuid: "648afde9-a999-492b-9d8d-5322763422ea",
    vendor:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Webapp3/6.0.0+861f7a908",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
};

const GUEST_CALL_JS = [
  {
    callType: "video",
    canControl: false,
    canChangeLayout: false,
    canDisconnect: true,
    canFecc: false,
    canMute: true,
    canRaiseHand: true,
    canSpotlight: true,
    canTransfer: true,
    displayName: "Richard Felix",
    overlayText: "Richard Felix",
    handRaisedTime: 0,
    identity: "753cecb0-e75a-4fe3-a32c-5339fe5dd290",
    isCameraMuted: true,
    isConjoined: false,
    isConnecting: false,
    isEndpoint: false,
    isExternal: false,
    isIdpAuthenticated: false,
    isGateway: false,
    isHost: false,
    isMainVideoDroppedOut: false,
    isMuted: true,
    isPresenting: false,
    isSpotlight: true,
    isStreaming: false,
    isVideoSilent: false,
    isWaiting: false,
    needsPresentationInMix: false,
    protocol: "",
    raisedHand: false,
    role: "guest",
    rxPresentation: true,
    serviceType: "conference",
    spotlightOrder: 1720545579.1636536,
    startAt: "2024-07-09T17:15:53.244Z",
    startTime: 1720545353.2444892,
    uri: "",
    uuid: "753cecb0-e75a-4fe3-a32c-5339fe5dd290",
    vendor: "",
    rawData: {
      api_url: "/participants/753cecb0-e75a-4fe3-a32c-5339fe5dd290",
      call_direction: "in",
      display_name: "Richard Felix",
      encryption: "On",
      has_media: true,
      is_muted: "YES",
      is_presenting: "NO",
      is_streaming_conference: false,
      is_video_call: "YES",
      is_audio_only_call: "NO",
      local_alias: "52569",
      overlay_text: "Richard Felix",
      presentation_supported: "YES",
      fecc_supported: "NO",
      protocol: "",
      role: "guest",
      rx_presentation_policy: "ALLOW",
      service_type: "conference",
      spotlight: 1720545579.1636536,
      start_time: 1720545353.2444892,
      uri: "",
      external_node_uuid: "",
      uuid: "753cecb0-e75a-4fe3-a32c-5339fe5dd290",
      vendor: "",
      is_external: false,
      is_conjoined: false,
      transfer_supported: "YES",
      disconnect_supported: "YES",
      mute_supported: "YES",
      buzz_time: 0,
      call_tag: "",
      is_video_muted: true,
      is_video_silent: false,
      is_main_video_dropped_out: false,
      needs_presentation_in_mix: false,
      show_live_captions: false,
      is_idp_authenticated: false,
      send_to_audio_mixes: [
        {
          mix_name: "main",
          prominent: false,
        },
      ],
      receive_from_audio_mix: "main",
      layout_group: null,
    },
  },
  {
    callType: "api",
    canControl: true,
    canChangeLayout: true,
    canDisconnect: true,
    canFecc: false,
    canMute: true,
    canRaiseHand: true,
    canSpotlight: true,
    canTransfer: true,
    displayName: "api_user",
    overlayText: "api_user",
    handRaisedTime: 0,
    identity: "3c57254a-66cf-4053-ace5-508282de0425",
    isCameraMuted: false,
    isConjoined: false,
    isConnecting: false,
    isEndpoint: false,
    isExternal: false,
    isIdpAuthenticated: false,
    isGateway: false,
    isHost: true,
    isMainVideoDroppedOut: false,
    isMuted: false,
    isPresenting: false,
    isSpotlight: false,
    isStreaming: false,
    isVideoSilent: false,
    isWaiting: false,
    needsPresentationInMix: false,
    protocol: "api",
    raisedHand: false,
    role: "chair",
    rxPresentation: true,
    serviceType: "conference",
    spotlightOrder: 0,
    startAt: "2024-07-09T17:18:57.185Z",
    startTime: 1720545537.1856968,
    uri: "api_user",
    uuid: "3c57254a-66cf-4053-ace5-508282de0425",
    vendor:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 PexRTC",
    rawData: {
      api_url: "/participants/3c57254a-66cf-4053-ace5-508282de0425",
      call_direction: "in",
      display_name: "api_user",
      encryption: "On",
      has_media: false,
      is_muted: "NO",
      is_presenting: "NO",
      is_streaming_conference: false,
      is_video_call: "NO",
      is_audio_only_call: "NO",
      local_alias: "52569",
      overlay_text: "api_user",
      presentation_supported: "NO",
      fecc_supported: "NO",
      protocol: "api",
      role: "chair",
      rx_presentation_policy: "ALLOW",
      service_type: "conference",
      spotlight: 0,
      start_time: 1720545537.1856968,
      uri: "api_user",
      external_node_uuid: "",
      uuid: "3c57254a-66cf-4053-ace5-508282de0425",
      vendor:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 PexRTC",
      is_external: false,
      is_conjoined: false,
      transfer_supported: "YES",
      disconnect_supported: "YES",
      mute_supported: "YES",
      buzz_time: 0,
      call_tag: "",
      is_video_muted: false,
      is_video_silent: false,
      is_main_video_dropped_out: false,
      needs_presentation_in_mix: false,
      show_live_captions: false,
      is_idp_authenticated: false,
      send_to_audio_mixes: [
        {
          mix_name: "main",
          prominent: false,
        },
      ],
      receive_from_audio_mix: "main",
      layout_group: null,
    },
  },
  {
    callType: "api",
    canControl: true,
    canChangeLayout: true,
    canDisconnect: true,
    canFecc: false,
    canMute: true,
    canRaiseHand: true,
    canSpotlight: true,
    canTransfer: true,
    displayName: "Primary Stream",
    overlayText: "Primary Stream",
    handRaisedTime: 0,
    identity: "091caf3c-b418-4d2b-94fd-041141244789",
    isCameraMuted: false,
    isConjoined: false,
    isConnecting: false,
    isEndpoint: false,
    isExternal: false,
    isIdpAuthenticated: false,
    isGateway: false,
    isHost: true,
    isMainVideoDroppedOut: false,
    isMuted: false,
    isPresenting: false,
    isSpotlight: false,
    isStreaming: true,
    isVideoSilent: false,
    isWaiting: false,
    needsPresentationInMix: false,
    protocol: "rtmp",
    raisedHand: false,
    role: "chair",
    rxPresentation: true,
    serviceType: "conference",
    spotlightOrder: 0,
    startAt: "2024-07-09T17:35:09.970Z",
    startTime: 1720546509.9707344,
    uri: "rtmp://alphaingest-us1.webcasts.com/abr_live/mp4:CAGXY2NQM9",
    uuid: "091caf3c-b418-4d2b-94fd-041141244789",
    vendor: "Unknown",
    rawData: {
      api_url: "/participants/091caf3c-b418-4d2b-94fd-041141244789",
      call_direction: "out",
      display_name: "Primary Stream",
      encryption: "Off",
      has_media: true,
      is_muted: "NO",
      is_presenting: "NO",
      is_streaming_conference: true,
      is_video_call: "NO",
      is_audio_only_call: "NO",
      local_alias: "52569",
      overlay_text: "Primary Stream",
      presentation_supported: "NO",
      fecc_supported: "NO",
      protocol: "rtmp",
      role: "chair",
      rx_presentation_policy: "ALLOW",
      service_type: "conference",
      spotlight: 0,
      start_time: 1720546509.9707344,
      uri: "rtmp://alphaingest-us1.webcasts.com/abr_live/mp4:CAGXY2NQM9",
      external_node_uuid: "",
      uuid: "091caf3c-b418-4d2b-94fd-041141244789",
      vendor: "Unknown",
      is_external: false,
      is_conjoined: false,
      transfer_supported: "YES",
      disconnect_supported: "YES",
      mute_supported: "YES",
      buzz_time: 0,
      call_tag: "",
      is_video_muted: false,
      is_video_silent: false,
      is_main_video_dropped_out: false,
      needs_presentation_in_mix: false,
      show_live_captions: false,
      is_idp_authenticated: false,
      send_to_audio_mixes: [
        {
          mix_name: "main",
          prominent: false,
        },
      ],
      receive_from_audio_mix: "main",
      layout_group: null,
    },
  },
];

const GUEST_CALL_API = [
  {
    api_url: "/participants/3c57254a-66cf-4053-ace5-508282de0425",
    call_direction: "in",
    display_name: "api_user",
    encryption: "On",
    has_media: false,
    is_muted: "NO",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "NO",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "api_user",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1720545537.1856968,
    uri: "",
    external_node_uuid: "",
    uuid: "3c57254a-66cf-4053-ace5-508282de0425",
    vendor: "",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/091caf3c-b418-4d2b-94fd-041141244789",
    call_direction: "out",
    display_name: "Primary Stream",
    encryption: "Off",
    has_media: true,
    is_muted: "NO",
    is_presenting: "NO",
    is_streaming_conference: true,
    is_video_call: "NO",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "Primary Stream",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1720546509.9707344,
    uri: "",
    external_node_uuid: "",
    uuid: "091caf3c-b418-4d2b-94fd-041141244789",
    vendor: "",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/6543933a-00a0-407a-80c6-fe4f83c64a31",
    call_direction: "out",
    display_name: "sip:presenter9@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    is_muted: "NO",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter9@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1720550333.480943,
    uri: "",
    external_node_uuid: "",
    uuid: "6543933a-00a0-407a-80c6-fe4f83c64a31",
    vendor: "",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/08a0e9f4-f095-4918-91f9-7997695a6ce7",
    call_direction: "out",
    display_name: "sip:presenter8@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    is_muted: "NO",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter8@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1720550341.510323,
    uri: "",
    external_node_uuid: "",
    uuid: "08a0e9f4-f095-4918-91f9-7997695a6ce7",
    vendor: "",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/732abb7b-4f97-4434-a61a-617dcc024a0d",
    call_direction: "out",
    display_name: "sip:presenter7@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    is_muted: "NO",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter7@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1720550351.5822287,
    uri: "",
    external_node_uuid: "",
    uuid: "732abb7b-4f97-4434-a61a-617dcc024a0d",
    vendor: "",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/7036cf94-66e9-4a1b-b948-5d4adcaff7c0",
    call_direction: "out",
    display_name: "sip:presenter1@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    is_muted: "NO",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter1@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1720550359.3752882,
    uri: "",
    external_node_uuid: "",
    uuid: "7036cf94-66e9-4a1b-b948-5d4adcaff7c0",
    vendor: "",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/e4930817-c8df-466a-a4cf-7b80610ffb1f",
    call_direction: "out",
    display_name: "sip:presenter4@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    is_muted: "NO",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter4@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1720550366.1096373,
    uri: "",
    external_node_uuid: "",
    uuid: "e4930817-c8df-466a-a4cf-7b80610ffb1f",
    vendor: "",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/9f7c505f-57f4-4e07-acdd-0836963df753",
    call_direction: "in",
    display_name: "Richard Felix",
    encryption: "On",
    has_media: true,
    is_muted: "YES",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "Richard Felix",
    presentation_supported: "YES",
    fecc_supported: "NO",
    protocol: "",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1720553626.5599737,
    uri: "",
    external_node_uuid: "",
    uuid: "9f7c505f-57f4-4e07-acdd-0836963df753",
    vendor: "",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: true,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
];

///////1 person a guest////////////
[
  {
    callType: "api",
    canControl: true,
    canChangeLayout: true,
    canDisconnect: true,
    canFecc: false,
    canMute: true,
    canRaiseHand: true,
    canSpotlight: true,
    canTransfer: true,
    displayName: "api_user",
    overlayText: "api_user",
    handRaisedTime: 0,
    identity: "39f62d18-cd3b-4a32-9c44-60dc5366480b",
    isCameraMuted: false,
    isConjoined: false,
    isConnecting: false,
    isEndpoint: false,
    isExternal: false,
    isIdpAuthenticated: false,
    isGateway: false,
    isHost: true,
    isMainVideoDroppedOut: false,
    isMuted: false,
    isPresenting: false,
    isSpotlight: false,
    isStreaming: false,
    isVideoSilent: false,
    isWaiting: false,
    needsPresentationInMix: false,
    protocol: "api",
    raisedHand: false,
    role: "chair",
    rxPresentation: true,
    serviceType: "conference",
    spotlightOrder: 0,
    startAt: "2024-07-16T23:16:42.557Z",
    startTime: 1721171802.5575755,
    uri: "api_user",
    uuid: "39f62d18-cd3b-4a32-9c44-60dc5366480b",
    vendor:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 PexRTC",
    rawData: {
      api_url: "/participants/39f62d18-cd3b-4a32-9c44-60dc5366480b",
      call_direction: "in",
      display_name: "api_user",
      encryption: "On",
      has_media: false,
      is_muted: "NO",
      is_presenting: "NO",
      is_streaming_conference: false,
      is_video_call: "NO",
      is_audio_only_call: "NO",
      local_alias: "52874",
      overlay_text: "api_user",
      presentation_supported: "NO",
      fecc_supported: "NO",
      protocol: "api",
      role: "chair",
      rx_presentation_policy: "ALLOW",
      service_type: "conference",
      spotlight: 0,
      start_time: 1721171802.5575755,
      uri: "api_user",
      external_node_uuid: "",
      uuid: "39f62d18-cd3b-4a32-9c44-60dc5366480b",
      vendor:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 PexRTC",
      is_external: false,
      is_conjoined: false,
      transfer_supported: "YES",
      disconnect_supported: "YES",
      mute_supported: "YES",
      buzz_time: 0,
      call_tag: "",
      is_video_muted: false,
      is_video_silent: false,
      is_main_video_dropped_out: false,
      needs_presentation_in_mix: false,
      show_live_captions: false,
      is_idp_authenticated: false,
      send_to_audio_mixes: [
        {
          mix_name: "main",
          prominent: false,
        },
      ],
      receive_from_audio_mix: "main",
      layout_group: null,
    },
    is_audio_only_call: false,
    has_media: false,
  },
  {
    callType: "video",
    canControl: false,
    canChangeLayout: false,
    canDisconnect: true,
    canFecc: false,
    canMute: true,
    canRaiseHand: true,
    canSpotlight: true,
    canTransfer: true,
    displayName: "Richard Felix",
    overlayText: "Make me a guest",
    handRaisedTime: 0,
    identity: "dcf1421c-bf4e-42a6-929b-9d02b7c5a668",
    isCameraMuted: true,
    isConjoined: false,
    isConnecting: false,
    isEndpoint: false,
    isExternal: false,
    isIdpAuthenticated: false,
    isGateway: false,
    isHost: false,
    isMainVideoDroppedOut: false,
    isMuted: true,
    isPresenting: false,
    isSpotlight: false,
    isStreaming: false,
    isVideoSilent: false,
    isWaiting: false,
    needsPresentationInMix: false,
    protocol: "",
    raisedHand: false,
    role: "guest",
    rxPresentation: true,
    serviceType: "conference",
    spotlightOrder: 0,
    startAt: "2024-07-16T23:38:53.903Z",
    startTime: 1721173133.9038925,
    uri: "",
    uuid: "dcf1421c-bf4e-42a6-929b-9d02b7c5a668",
    vendor: "",
    rawData: {
      api_url: "/participants/dcf1421c-bf4e-42a6-929b-9d02b7c5a668",
      call_direction: "in",
      display_name: "Richard Felix",
      encryption: "On",
      has_media: true,
      is_muted: "YES",
      is_presenting: "NO",
      is_streaming_conference: false,
      is_video_call: "YES",
      is_audio_only_call: "NO",
      local_alias: "52874",
      overlay_text: "Make me a guest",
      presentation_supported: "YES",
      fecc_supported: "NO",
      protocol: "",
      role: "guest",
      rx_presentation_policy: "ALLOW",
      service_type: "conference",
      spotlight: 0,
      start_time: 1721173133.9038925,
      uri: "",
      external_node_uuid: "",
      uuid: "dcf1421c-bf4e-42a6-929b-9d02b7c5a668",
      vendor: "",
      is_external: false,
      is_conjoined: false,
      transfer_supported: "YES",
      disconnect_supported: "YES",
      mute_supported: "YES",
      buzz_time: 0,
      call_tag: "",
      is_video_muted: true,
      is_video_silent: false,
      is_main_video_dropped_out: false,
      needs_presentation_in_mix: false,
      show_live_captions: false,
      is_idp_authenticated: false,
      send_to_audio_mixes: [
        {
          mix_name: "main",
          prominent: false,
        },
      ],
      receive_from_audio_mix: "main",
      layout_group: null,
    },
    is_audio_only_call: false,
    has_media: true,
  },
  {
    callType: "video",
    canControl: false,
    canChangeLayout: false,
    canDisconnect: true,
    canFecc: false,
    canMute: true,
    canRaiseHand: true,
    canSpotlight: true,
    canTransfer: true,
    displayName: "sip:presenter9@prodfs.webcasts.com",
    overlayText: "presenter9@prodfs.webcasts.com",
    handRaisedTime: 0,
    identity: "3978f818-327c-4512-bacf-2b68c797115b",
    isCameraMuted: false,
    isConjoined: false,
    isConnecting: false,
    isEndpoint: true,
    isExternal: false,
    isIdpAuthenticated: false,
    isGateway: false,
    isHost: false,
    isMainVideoDroppedOut: false,
    isMuted: false,
    isPresenting: false,
    isSpotlight: false,
    isStreaming: false,
    isVideoSilent: false,
    isWaiting: false,
    needsPresentationInMix: false,
    protocol: "sip",
    raisedHand: false,
    role: "guest",
    rxPresentation: true,
    serviceType: "conference",
    spotlightOrder: 0,
    startAt: "2024-07-16T23:39:17.792Z",
    startTime: 1721173157.7926688,
    uri: "sip:presenter9@prodfs.webcasts.com",
    uuid: "3978f818-327c-4512-bacf-2b68c797115b",
    vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
    rawData: {
      api_url: "/participants/3978f818-327c-4512-bacf-2b68c797115b",
      call_direction: "out",
      display_name: "sip:presenter9@prodfs.webcasts.com",
      encryption: "On",
      has_media: true,
      is_muted: "NO",
      is_presenting: "NO",
      is_streaming_conference: false,
      is_video_call: "YES",
      is_audio_only_call: "NO",
      local_alias: "52874",
      overlay_text: "presenter9@prodfs.webcasts.com",
      presentation_supported: "NO",
      fecc_supported: "NO",
      protocol: "sip",
      role: "guest",
      rx_presentation_policy: "ALLOW",
      service_type: "conference",
      spotlight: 0,
      start_time: 1721173157.7926688,
      uri: "sip:presenter9@prodfs.webcasts.com",
      external_node_uuid: "",
      uuid: "3978f818-327c-4512-bacf-2b68c797115b",
      vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
      is_external: false,
      is_conjoined: false,
      transfer_supported: "YES",
      disconnect_supported: "YES",
      mute_supported: "YES",
      buzz_time: 0,
      call_tag: "",
      is_video_muted: false,
      is_video_silent: false,
      is_main_video_dropped_out: false,
      needs_presentation_in_mix: false,
      show_live_captions: false,
      is_idp_authenticated: false,
      send_to_audio_mixes: [
        {
          mix_name: "main",
          prominent: false,
        },
      ],
      receive_from_audio_mix: "main",
      layout_group: null,
    },
    is_audio_only_call: false,
    has_media: true,
  },
  {
    callType: "video",
    canControl: true,
    canChangeLayout: true,
    canDisconnect: true,
    canFecc: false,
    canMute: true,
    canRaiseHand: true,
    canSpotlight: true,
    canTransfer: true,
    displayName: "Richard Felix",
    overlayText: "Richard Felix",
    handRaisedTime: 0,
    identity: "29cd65a9-5331-42a8-afe3-57c3b29f6c66",
    isCameraMuted: true,
    isConjoined: false,
    isConnecting: false,
    isEndpoint: false,
    isExternal: false,
    isIdpAuthenticated: false,
    isGateway: false,
    isHost: true,
    isMainVideoDroppedOut: false,
    isMuted: true,
    isPresenting: false,
    isSpotlight: false,
    isStreaming: false,
    isVideoSilent: false,
    isWaiting: false,
    needsPresentationInMix: false,
    protocol: "webrtc",
    raisedHand: false,
    role: "chair",
    rxPresentation: true,
    serviceType: "conference",
    spotlightOrder: 0,
    startAt: "2024-07-16T23:42:18.775Z",
    startTime: 1721173338.7752151,
    uri: "Richard Felix",
    uuid: "29cd65a9-5331-42a8-afe3-57c3b29f6c66",
    vendor:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Webapp3/6.0.0+861f7a908",
    rawData: {
      api_url: "/participants/29cd65a9-5331-42a8-afe3-57c3b29f6c66",
      call_direction: "in",
      display_name: "Richard Felix",
      encryption: "On",
      has_media: true,
      is_muted: "YES",
      is_presenting: "NO",
      is_streaming_conference: false,
      is_video_call: "YES",
      is_audio_only_call: "NO",
      local_alias: "52874",
      overlay_text: "Richard Felix",
      presentation_supported: "YES",
      fecc_supported: "NO",
      protocol: "webrtc",
      role: "chair",
      rx_presentation_policy: "ALLOW",
      service_type: "conference",
      spotlight: 0,
      start_time: 1721173338.7752151,
      uri: "Richard Felix",
      external_node_uuid: "",
      uuid: "29cd65a9-5331-42a8-afe3-57c3b29f6c66",
      vendor:
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Webapp3/6.0.0+861f7a908",
      is_external: false,
      is_conjoined: false,
      transfer_supported: "YES",
      disconnect_supported: "YES",
      mute_supported: "YES",
      buzz_time: 0,
      call_tag: "",
      is_video_muted: true,
      is_video_silent: false,
      is_main_video_dropped_out: false,
      needs_presentation_in_mix: false,
      show_live_captions: false,
      is_idp_authenticated: false,
      send_to_audio_mixes: [
        {
          mix_name: "main",
          prominent: false,
        },
      ],
      receive_from_audio_mix: "main",
      layout_group: null,
    },
    is_audio_only_call: false,
    has_media: true,
  },
];
